#!/usr/bin/env python3
"""
DSLighting Titanic 比赛运行示例

展示如何使用 DSLighting 来解决 Kaggle Titanic 比赛
"""

import sys
import os
from pathlib import Path

# 添加项目根目录到 Python 路径
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

import dslighting

def main():
    print("="*80)
    print("DSLighting - Titanic 比赛示例")
    print("="*80)
    print()

    # ==================== 方式 1: 使用 task_id（推荐） ====================
    print("方式 1: 使用 task_id（需要先配置 registry）")
    print("-" * 80)

    # 如果已经在 dslighting/registry/titanic/ 配置好了
    # 可以直接使用 task_id
    try:
        print("\n正在加载数据...")
        data = dslighting.load_data("titanic")
        print(f"✅ 数据加载成功: {data}")
        print()

        # 显示数据信息
        print(data.show())
        print()

        # 运行 Agent
        print("正在运行 Agent...")
        agent = dslighting.Agent()

        result = agent.run(
            data,
            model="openai/gpt-4",  # 或 "gpt-3.5-turbo" 以节省成本
            workflow="aide",  # 可选: aide, autokaggle, data_interpreter
            max_iterations=5,  # 限制迭代次数
        )

        # 显示结果
        print("\n" + "="*80)
        print("🎯 运行结果")
        print("="*80)
        print(f"分数: {result.score}")
        print(f"提交文件: {result.output_path}")
        print(f"运行时间: {result.metadata.get('duration', 'N/A')}")
        print()

    except Exception as e:
        print(f"❌ 方式 1 失败: {e}")
        print("提示: 请确保已在 dslighting/registry/titanic/ 创建配置文件")
        print()

    # ==================== 方式 2: 直接指定数据路径 ====================
    print("\n" + "="*80)
    print("方式 2: 直接指定数据路径")
    print("-" * 80)

    try:
        # 指定数据目录
        data_dir = project_root / "data/competitions/titanic"

        if not data_dir.exists():
            print(f"❌ 数据目录不存在: {data_dir}")
            print("\n请先运行: python prepare_data.py")
            return

        print(f"\n正在加载数据: {data_dir}")
        data = dslighting.load_data(data_dir)

        # 显示数据信息
        print("\n数据信息:")
        print(f"  Task ID: {data.task_id}")
        print(f"  Task Type: {data.get_task_type()}")
        print(f"  Data Dir: {data.data_dir}")
        print()

        # 创建 Agent 并运行
        print("正在运行 Agent...")
        agent = dslighting.Agent()

        result = agent.run(
            data,
            model="openai/gpt-4",
            workflow="aide",
            max_iterations=3,  # 示例使用较少迭代
        )

        # 显示结果
        print("\n" + "="*80)
        print("🎯 运行结果")
        print("="*80)
        print(f"分数: {result.score}")
        print(f"提交文件: {result.output_path}")
        print()

        # 显示提交文件内容
        if result.output_path and Path(result.output_path).exists():
            import pandas as pd
            submission = pd.read_csv(result.output_path)
            print("提交文件预览:")
            print(submission.head(10))
            print()

    except Exception as e:
        print(f"❌ 方式 2 失败: {e}")
        import traceback
        traceback.print_exc()

    # ==================== 提交到 Kaggle ====================
    print("\n" + "="*80)
    print("📤 提交到 Kaggle")
    print("="*80)
    print("\n提交命令:")
    print("kaggle competitions submit -c titanic \\")
    print("  -f <submission_file> \\")
    print("  -m 'Generated by DSLighting'")
    print()

if __name__ == "__main__":
    main()
