import logging
import difflib
from pathlib import Path
from typing import Dict, Any, List, Tuple

from dslighting.workflows.base import BaseWorkflow
from dslighting.state.dsagent import DSAgentState
from dslighting.runtime.dag import BaseWorkflowActor, NodeResult, OpNode

from dslighting.services.sandbox import SandboxService
from dslighting.ops.base import Operator


logger = logging.getLogger(__name__)


class DSAgentWorkflowDagActor(BaseWorkflowActor):
    """
    DAG actor for DS-Agent workflow.

    DS-Agent uses a simple Plan-Execute-Log loop:
    1. Plan: Generate a plan based on the problem and running log
    2. Execute: Refine code based on the plan and execute it
    3. Log: Update the running log with the plan, execution result, and diff

    DAG structure (dynamically generated):
    plan_0 ──→ exec_0 ──→ log_0 ──→ plan_1 ──→ exec_1 ──→ log_1 ──→ ... ──→ finalize
    """

    def __init__(
        self,
        *,
        task_id: str,
        workflow: "DSAgentWorkflow",
        description: str,
        io_instructions: str,
        output_path: Path,
        enable_debug_branch: bool = False,
        max_retries: int = 2,
    ) -> None:
        self.task_id = task_id
        self.workflow = workflow
        self.output_path = output_path
        self.task_goal = description
        self.io_instructions = io_instructions
        self.max_iterations = max(1, int(workflow.agent_config.get("max_iterations", 2)))
        self.max_retries = max_retries

        self._done = False
        self._final_result: Dict[str, Any] = {}
        # Per-task, isolated state
        self._running_log: str = "[Initial State] Starting analysis."
        self._final_code: str = (
            "# Basic Initialization. Analyze the data report and I/O requirements."
        )
        self._last_plan: str = ""  # Stores plan generated by current step's plan node
        self._current_step_retries: Dict[
            int, int
        ] = {}  # Tracks retries for the current P-E-L cycle

    def _plan_node_id(self, step: int) -> str:
        return f"{self.task_id}:dsagent_plan:{step}"

    def _exec_node_id(self, step: int) -> str:
        return f"{self.task_id}:dsagent_exec:{step}"

    def _log_node_id(self, step: int) -> str:
        return f"{self.task_id}:dsagent_log:{step}"

    def _finalize_node_id(self) -> str:
        return f"{self.task_id}:dsagent_finalize"

    def _build_plan_node(self, step: int, depends_on: List[str]) -> OpNode:
        """Plan node: generate a plan based on problem and running log"""
        return OpNode(
            node_id=self._plan_node_id(step),
            task_id=self.task_id,
            op_type="llm",
            operator_name="planner",
            depends_on=depends_on,
            payload={
                "callable": self.workflow.planner_op,
                "kwargs": {
                    "research_problem": self.task_goal,
                    "io_instructions": self.io_instructions,
                    "running_log": self._running_log,  # Use isolated state
                },
            },
            state_version=step,
            priority=10,
            estimated_runtime_seconds=15.0,
        )

    def _build_exec_node(self, step: int, depends_on: List[str]) -> OpNode:
        """Execute node: refine code based on plan and execute it"""
        return OpNode(
            node_id=self._exec_node_id(step),
            task_id=self.task_id,
            op_type="sandbox",
            operator_name="executor",
            depends_on=depends_on,
            payload={
                "callable": self.workflow.executor_op,
                "kwargs": {
                    "initial_code": self._final_code,  # Use isolated state
                    "plan": self._last_plan,  # Use isolated state
                    "research_problem": self.task_goal,
                    "io_instructions": self.io_instructions,
                    "running_log": self._running_log,  # Use isolated state
                },
            },
            state_version=step,
            priority=5,
            estimated_runtime_seconds=30.0,
        )

    def _build_log_node(
        self, step: int, plan: str, exec_result: Dict[str, Any], diff: str, depends_on: List[str]
    ) -> OpNode:
        """Log node: update running log with plan, execution result, and diff"""
        return OpNode(
            node_id=self._log_node_id(step),
            task_id=self.task_id,
            op_type="llm",
            operator_name="logger",
            depends_on=depends_on,
            payload={
                "callable": self.workflow.logger_op,
                "kwargs": {
                    "running_log": self._running_log,  # Use isolated state
                    "plan": plan,
                    "exec_result": exec_result,
                    "diff": diff,
                },
            },
            state_version=step,
            priority=3,
            estimated_runtime_seconds=10.0,
        )

    def _build_finalize_node(self, depends_on: List[str]) -> OpNode:
        """Finalize node: execute the final code to produce output file"""
        return OpNode(
            node_id=self._finalize_node_id(),
            task_id=self.task_id,
            op_type="sandbox",
            operator_name="finalize",
            depends_on=depends_on,
            payload={
                "callable": self._finalize_execution,
                "kwargs": {
                    "output_path": self.output_path,
                },
            },
            state_version=self.max_iterations,
            priority=1,
            estimated_runtime_seconds=30.0,
        )

    async def _finalize_execution(self, output_path: Path) -> Dict[str, Any]:
        """Execute the final refined code to produce the output file"""
        logger.info("Max iterations reached. Executing the final refined code...")

        final_exec_result = await self.workflow.sandbox_service.run_script(
            self._final_code  # Use isolated state
        )

        if not final_exec_result.success:
            logger.error(f"Final code execution failed!\n{final_exec_result.stderr}")
            return {
                "success": False,
                "error": final_exec_result.stderr,
                "status": "failed",
            }

        return {
            "success": True,
            "stdout": final_exec_result.stdout,
            "stderr": final_exec_result.stderr,
            "final_code": self._final_code,  # Use isolated state
            "running_log": self._running_log,  # Use isolated state
            "status": "success",
        }

    def initial_nodes(self) -> List[OpNode]:
        """Initial node: first Plan"""
        return [self._build_plan_node(step=0, depends_on=[])]

    def on_node_result(self, result: NodeResult) -> Tuple[List[OpNode], bool]:
        node_id = result.node_id
        try:
            step = int(node_id.split(":")[-1])
        except (ValueError, IndexError):
            step = -1  # Finalize node or other format

        if node_id.startswith(f"{self.task_id}:dsagent_plan:"):
            return self._handle_plan_result(step, result)

        elif node_id.startswith(f"{self.task_id}:dsagent_exec:"):
            return self._handle_exec_result(step, result)

        elif node_id.startswith(f"{self.task_id}:dsagent_log:"):
            return self._handle_log_result(step, result)

        elif node_id == self._finalize_node_id():
            self._done = True
            self._final_result = dict(result.outputs or {})
            self._final_result["status"] = (
                result.outputs.get("status", "success") if result.outputs else "unknown"
            )
            return [], True

        logger.warning(f"Unhandled node result for ID: {node_id}. Finishing workflow.")
        return [], True

    def _handle_plan_result(self, step: int, result: NodeResult) -> Tuple[List[OpNode], bool]:
        if result.status == "success":
            plan = result.outputs.get("plan", "")
            if not plan:
                logger.warning(
                    f"Plan_{step} returned empty plan. Triggering retry for step {step}."
                )
                return self._handle_step_failure(step, result.node_id)

            self._last_plan = plan  # Update isolated state

            return [self._build_exec_node(step=step, depends_on=[result.node_id])], False
        else:
            return self._handle_step_failure(step, result.node_id)

    def _handle_exec_result(self, step: int, result: NodeResult) -> Tuple[List[OpNode], bool]:
        if result.status == "success":
            refined_code = result.outputs.get("refined_code", "")
            if not refined_code:
                logger.warning(
                    f"Exec_{step} returned empty refined code. Triggering retry for step {step}."
                )
                return self._handle_step_failure(step, result.node_id)

            # Retrieve initial_code from outputs (passed through by executor_op)
            initial_code_for_diff = result.outputs.get("initial_code", "")

            # Update isolated state with new refined code
            self._final_code = refined_code

            exec_result_dict = result.outputs.get("exec_result", {})

            diff = "".join(
                difflib.unified_diff(
                    initial_code_for_diff.splitlines(
                        keepends=True
                    ),  # Use the code from before execution
                    refined_code.splitlines(keepends=True),  # Code from this exec result
                    fromfile="a/old_code.py",
                    tofile="b/new_code.py",
                )
            )

            plan = self._last_plan  # Use isolated state

            return [
                self._build_log_node(
                    step=step,
                    plan=plan,
                    exec_result=exec_result_dict,
                    diff=diff,
                    depends_on=[result.node_id],
                )
            ], False
        else:
            logger.warning(f"Exec_{step} failed. Triggering retry for step {step}.")
            return self._handle_step_failure(step, result.node_id)

    def _handle_log_result(self, step: int, result: NodeResult) -> Tuple[List[OpNode], bool]:
        if result.status == "success":
            new_log_entry = result.outputs.get("new_log_entry", "")
            if not new_log_entry:
                logger.warning(
                    f"Log_{step} returned empty log entry. Triggering retry for step {step}."
                )
                return self._handle_step_failure(step, result.node_id)

            self._running_log = new_log_entry  # Update isolated state

            return self._trigger_next_iteration_or_finalize(step, result.node_id)
        else:
            logger.warning(f"Log_{step} failed. Triggering retry for step {step}.")
            return self._handle_step_failure(step, result.node_id)

    def _handle_step_failure(self, step: int, from_node_id: str) -> Tuple[List[OpNode], bool]:
        self._current_step_retries[step] = self._current_step_retries.get(step, 0) + 1
        if self._current_step_retries[step] < self.max_retries:
            logger.info(
                f"Retrying step {step} (attempt {self._current_step_retries[step]}/{self.max_retries}) by re-planning."
            )
            # Restart the current P-E-L cycle from Plan
            return [self._build_plan_node(step=step, depends_on=[from_node_id])], False
        else:
            logger.error(
                f"Step {step} failed after {self.max_retries} retries. Finishing workflow."
            )
            self._done = True
            self._final_result = {
                "status": "failed",
                "error": f"Step {step} failed after {self.max_retries} retries.",
            }
            return [], True

    def _trigger_next_iteration_or_finalize(
        self, step: int, from_node_id: str
    ) -> Tuple[List[OpNode], bool]:
        next_step = step + 1
        if next_step < self.max_iterations:
            logger.info(
                f"Step {step} completed successfully. Proceeding to Plan for step {next_step}."
            )
            return [self._build_plan_node(step=next_step, depends_on=[from_node_id])], False
        else:
            logger.info("Max iterations reached. Triggering finalize node.")
            return [self._build_finalize_node(depends_on=[from_node_id])], False

    def get_result(self) -> Any:
        return dict(self._final_result)


class DSAgentWorkflow(BaseWorkflow):
    """
    Implements the core algorithmic loop of DS-Agent: Plan -> Execute -> Log.
    This workflow now conforms to the BaseWorkflow interface.
    """

    def __init__(
        self, operators: Dict[str, Operator], services: Dict[str, Any], agent_config: Dict[str, Any]
    ):
        super().__init__(operators, services, agent_config)

        # Validate required services
        required_services = ["state", "sandbox"]
        for service_name in required_services:
            if service_name not in services:
                raise ValueError(f"DSAgentWorkflow requires '{service_name}' service")

        # Validate required operators
        required_operators = ["planner", "executor", "logger"]
        for op_name in required_operators:
            if op_name not in operators:
                raise ValueError(f"DSAgentWorkflow requires '{op_name}' operator")

        self.state: DSAgentState = services["state"]
        self.sandbox_service: SandboxService = services["sandbox"]
        self.planner_op = self.operators["planner"]
        self.executor_op = self.operators["executor"]
        self.logger_op = self.operators["logger"]

    def build_actor(
        self,
        *,
        task_id: str,
        description: str,
        io_instructions: str,
        data_dir: Path,
        output_path: Path,
    ) -> DSAgentWorkflowDagActor:
        _ = data_dir
        search_cfg = self.agent_config.get("search", {})
        max_retries = search_cfg.get("max_retries", 2)
        return DSAgentWorkflowDagActor(
            task_id=task_id,
            workflow=self,
            description=description,
            io_instructions=io_instructions,
            output_path=output_path,
            max_retries=max_retries,
        )

    async def solve(
        self, description: str, io_instructions: str, data_dir: Path, output_path: Path
    ) -> None:
        """
        Use DS-Agent's Plan-Execute-Log loop...
        """
        logger.info(f"DSAgentWorkflow starting to solve task. Target output: {output_path}")

        self.state.running_log = "[Initial State] Starting analysis."
        self.state.final_code = (
            "# Basic Initialization. Analyze the data report and I/O requirements."
        )

        task_goal = description
        current_io_instructions = io_instructions

        max_iterations = self.agent_config.get("max_iterations", 2)

        for step in range(max_iterations):
            logger.info(f"--- Starting DS-Agent Solve Step {step + 1}/{max_iterations} ---")

            # 1. Plan
            plan = await self.planner_op(
                research_problem=task_goal,
                io_instructions=current_io_instructions,
                running_log=self.state.running_log,
            )

            # 2. Execute (refine the code)
            initial_code = self.state.final_code
            exec_result, refined_code = await self.executor_op(
                initial_code=initial_code,
                plan=plan,
                research_problem=task_goal,
                io_instructions=current_io_instructions,
                running_log=self.state.running_log,
            )

            diff = "".join(
                difflib.unified_diff(
                    initial_code.splitlines(keepends=True),
                    refined_code.splitlines(keepends=True),
                )
            )

            # 3. Log
            new_log_entry = await self.logger_op(
                running_log=self.state.running_log, plan=plan, exec_result=exec_result, diff=diff
            )

            self.state.running_log = new_log_entry

            self.state.final_code = refined_code
            logger.info(f"Step {step + 1} complete. Code has been refined.")

        logger.info(
            "Max iterations reached. Executing the final refined code to produce the output file..."
        )
        final_exec_result = await self.sandbox_service.run_script(self.state.final_code)

        if not final_exec_result.success:
            logger.error(f"Final code execution failed!\n{final_exec_result.stderr}")
            return self.state

        logger.info(f"Successfully executed final code. Output should be at {output_path}")
        return self.state
